" Few basics:
syntax on
set encoding=utf-8
set number relativenumber
set nocompatible
set splitright

"""--- Custom binds ---"""

" sorround selection with quotes
vnoremap s" c"<C-r>""<ESC>
vnoremap s' c'<C-r>"'<ESC>

" sorround selection with brackets
vnoremap s( c(<C-r>")<ESC>
vnoremap s{ c{<C-r>"}<ESC>
vnoremap s[ c[<C-r>"]<ESC>

" Copy to system clipboard
vnoremap  <leader>y  "+y
nnoremap  <leader>Y  "+yg_
nnoremap  <leader>y  "+y
nnoremap  <leader>yy  "+yy

" " Paste from system clipboard
nnoremap <leader>p "+p
nnoremap <leader>P "+P
vnoremap <leader>p "+p
vnoremap <leader>P "+P

"""--- end custom mappings ---"""

" Open Current File in browser
command OpenInBrave :!brave %:p

" Remove gitbash vim's visual bell
set novisualbell

" Setting view dir to the one in $HOME
set viewdir=C:\Users\Davinder\vimfiles\view

" Set background
set background=dark

" Backspace fix for windows
set bs=2

" Turn tabs to spaces
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent

" Don't fk up makefiles
autocmd FileType make :setlocal noexpandtab

" Making Folds Persist
" autocmd BufWinLeave *{.,_}* mkview
autocmd BufWinEnter *{.,_}* silent loadview

" Remove relative numbers in insert mode
autocmd InsertEnter * :set norelativenumber
autocmd InsertLeave * :set relativenumber

" Automatically Delete Trailing Whitespace on save.
autocmd BufWritePre * %s/\s\+$//e

" Format Python files on save
autocmd BufWritePre *.py :norm gggqG``zz

" Auto close brackets and strings
function! AutoCloseBracketAndStrings()
  inoremap <buffer> " ""<left>
  inoremap <buffer> ' ''<left>
  inoremap <buffer> ( ()<left>
  inoremap <buffer> [ []<left>
  inoremap <buffer> { {}<left>
  inoremap <buffer> {<CR> {<CR>}<ESC>O
endfunction

autocmd FileType html,css,scss call AutoCloseBracketAndStrings()

" Recursive search
" Tab complete for every file related tasks
set path+=**

" Display all matches on tab complete
set wildmenu

" File explorer settings
let g:netrw_banner=0 " removes huge banner
let g:netrw_liststyle=3 " fix view to tree
let g:netrw_browse_split=4 " opens in prior window
let g:netrw_altv=1 " opens splits to the right
